                                              
                                              **Taller #1 analisis de datos**

### Ejercicio 2

Dataset: https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user

1. Importar el dataset, asignarlo a una variable llamada *users* y usar el *user_id* como índice.
2. ¿Cuál es el número de observaciones y columnas en el dataset?
3. Mostrar el nombre de las columnas y el tipo de dato que contiene.
4. Mostrar la indexación del dataset.
5. ¿Cuántas ocupaciones diferentes hay en este conjunto de datos?
6. ¿Cuál es la ocupación más frecuente?
7. ¿Cuál es la edad media de los usuarios?
8. ¿Cuál es la edad con menos ocurrencia?

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Lectura de una base de datos en internet y asignación a la variable users.
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep='|', index_col='user_id')

In [ ]:
# Mostrar en pantalla las 10 primeras filas del dataFrame
users.head(10)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703

In [ ]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [ ]:
# Tamaño del dataframe
users.shape

(943, 4)

In [ ]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [ ]:
#Obtener un resumen conciso de los datos almacenados en el dataFrame
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

In [ ]:
# Indexar

In [ ]:
users[users.occupation == "writer"].count()

age           45
gender        45
occupation    45
zip_code      45
dtype: int64

In [ ]:
# Para mostrar el número de ocupaciones diferentes
num_ocupaciones_diferentes = users['occupation'].nunique()
print(f"El número de ocupaciones diferentes es: {num_ocupaciones_diferentes}")

El número de ocupaciones diferentes es: 21

In [ ]:
users.groupby("occupation").max()

               age gender zip_code
occupation
administrator   70      M    V1G4L
artist          48      M    V5A2B
doctor          64      M    97405
educator        63      M    M4J2K
engineer        70      M    T8H1N
entertainment   50      M    V3N4P
executive       69      M    L1V3W
healthcare      62      M    97232
homemaker       50      M    96349
lawyer          53      M    90703
librarian       69      M    99603
marketing       55      M    97215
none            55      M    94619
other           64      M    V0R2M
programmer      63      M    98121
retired         73      M    98257
salesman        66      M    97408
scientist       55      M    T8H1N
student         42      M    R3T5K
technician      55      M    Y1A6B
writer          60      M    E2A4H

In [ ]:
# frecuencia de ocupaciones
users['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [ ]:
users["age"].mean()

np.float64(34.05196182396607)

In [ ]:
users['age'].value_counts()

age
30    39
25    38
22    37
28    36
27    35
      ..
7      1
11     1
66     1
10     1
73     1
Name: count, Length: 61, dtype: int64

### Ejercicio 3

Diccionario dado:

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}
            
1. Crea un DataFrame llamado *army* a partir del diccionario dado

(No olvide incluir los nombres de las columnas en el orden presentado en el diccionario ('regimen', 'company', ...) para que el orden del índice de la columna sea coherente con las soluciones. Si se omite, Pandas ordenará las columnas alfabéticamente.

2. Establezca la columna 'origin' como índice del dataset.
3. Imprima las columnas 'veterans' y 'deaths'
4. Seleccione las columnas 'deaths', 'size' y 'deserters' de Maine a Alaska.
5. Seleccione la tercera columna hasta la séptima columna.
6. Seleccione las filas donde *deaths* sea mayor que 50.
7. Seleccione las filas donde *deaths* sea mayor que 500 o menor que 50.
8. Selecciona todos los *regiments* no nombrados *Dragoons*.
9. Seleccione la tercera celda en la fila llamada *Arizona*
10. Seleccione la tercera celda en la columna llamada *deaths*

In [ ]:
# Lectura de una base de datos en internet y asignación a la variable users.
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35], 'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9], 'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523], 'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345], 'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3], 'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1], 'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3], 'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

In [ ]:
raw_data

{'regiment': ['Nighthawks',
  'Nighthawks',
  'Nighthawks',
  'Nighthawks',
  'Dragoons',
  'Dragoons',
  'Dragoons',
  'Dragoons',
  'Scouts',
  'Scouts',
  'Scouts',
  'Scouts'],
 'company': ['1st',
  '1st',
  '2nd',
  '2nd',
  '1st',
  '1st',
  '2nd',
  '2nd',
  '1st',
  '1st',
  '2nd',
  '2nd'],
 'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
 'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
 'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
 'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
 'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
 'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
 'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
 'origin': ['Arizona',
  'California',
  'Texas',
  'Florida',
  'Maine',
  'Iowa',
  'Alaska',
  'Washington',
  'Oregon',
  'Wyoming',
  'Louisana',
  'Georgia']}

In [ ]:
army = pd.DataFrame(raw_data, columns=['regiment', 'company', 'deaths', 'battles', 'size', 'veterans', 'readiness', 'armored', 'deserters', 'origin'])
display(army.head())

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine

In [ ]:
army = army.set_index('origin')
display(army.head())

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3

In [ ]:
print(army[['veterans', 'deaths']])

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

In [ ]:
# columnas 'deaths', 'size' y 'deserters' de Maine a Alaska
army.loc['Maine':'Alaska', ['deaths', 'size', 'deserters']]

        deaths  size  deserters
origin
Maine       43  1592          3
Iowa       234  1006          4
Alaska     523   987         24

In [ ]:
# Consultar los datos de las columnas 3 a
army.iloc[:,4:8]

            size  veterans  readiness  armored
origin
Arizona     1045         1          1        1
California   957         5          2        0
Texas       1099        62          3        1
Florida     1400        26          3        1
Maine       1592        73          2        0
Iowa        1006        37          1        1
Alaska       987       949          2        0
Washington   849        48          3        1
Oregon       973        48          2        0
Wyoming     1005       435          1        0
Louisana    1099        63          2        1
Georgia     1523       345          3        1

In [ ]:
# filas donde deaths sea mayor que 50
army[army.deaths > 50]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

In [ ]:
#filas donde deaths sea mayor que 500 o menor que 50.
army[army.deaths > 500]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Alaska,Dragoons,2nd,523,8,987,949,2,0,24

In [ ]:
army1=army[army.deaths > 500]
army2=army[army.deaths <50]
army1

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Alaska,Dragoons,2nd,523,8,987,949,2,0,24

In [ ]:
army2

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [ ]:
# Concatenar por filas
all_data = pd.concat([army1, army2])
all_data

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [ ]:
 #todos los regiments no nombrados Dragoons.

army[army.regiment != "Dragoons"]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

In [ ]:
 #Tercera celda en la fila llamada Arizona
army.loc["Arizona",:].iloc[2]

np.int64(523)

In [ ]:
 #tercera celda en la columna llamada deaths
army.loc[:,"deaths"].iloc[2]

np.int64(25)